### ISSUE TITLE
stripslashes in "save" shortens content in some cases

### ISSUE THREAD

**Issue by namvan** [panicsteve/w2wiki#4]
Hi Steve, 
First thing first, love your w2wiki so much and thank you so much for creating a simple but elegant solution.
This behaviour happens when I did as below
- Add a new content with some code which contains backslashes in code section (back tick)
- Save it
- All backslashes got removed.
- Edit it, re-add backslashed but double them this time.
- Save it. And now the view show the intended text.
- One of the two backslashes remains at each occurence.
-  Edit again but not doing anything.
- Save it
- All backslashes are now gone.

I tried to remove that stripslashes call and all content looks fine. Any rationale for that call?
Cheers,
Nam

**Comment by panicsteve** [comment]
It's been years since I last looked at this code, but as far as I can tell, that call is not necessary.  My hypothesis is, way back when I wrote this, I was using a much older version of PHP or a PHP config that automatically added escape slashes to all form inputs, and the purpose of that call was to remove those.

There's no SQL, so there's no risk of SQL injection.  :)  So I think, if it's working well for you, it's fine to take that out.

**Comment by codeling** [comment]
I believe this is already fixed by https://github.com/panicsteve/w2wiki/commit/6826cb062fb1a0cc278e8aa7976be25316a8879c and can therefore be closed...
